-- 1. 여행 일정(travel_schedules) 테이블 생성
CREATE TABLE travel_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Row Level Security (RLS) 활성화
ALTER TABLE travel_schedules ENABLE ROW LEVEL SECURITY;

-- 3. 누구나 데이터를 읽을 수 있도록 정책 설정
CREATE POLICY "Enable read access for all users" 
ON travel_schedules 
FOR SELECT 
USING (true);

-- 4. 누구나 데이터를 추가할 수 있도록 정책 설정
CREATE POLICY "Enable insert for all users" 
ON travel_schedules 
FOR INSERT 
WITH CHECK (true);

-- 5. 누구나 데이터를 수정할 수 있도록 정책 설정
CREATE POLICY "Enable update for all users" 
ON travel_schedules 
FOR UPDATE 
USING (true);

-- 6. 누구나 데이터를 삭제할 수 있도록 정책 설정
CREATE POLICY "Enable delete for all users" 
ON travel_schedules 
FOR DELETE 
USING (true);

-- 7. 날짜 컬럼을 필수가 아니도록 변경 (미정/불참 상태 지원)
ALTER TABLE travel_schedules ALTER COLUMN start_date DROP NOT NULL;
ALTER TABLE travel_schedules ALTER COLUMN end_date DROP NOT NULL;

-- 8. 참석 상태 컬럼 추가
ALTER TABLE travel_schedules ADD COLUMN IF NOT EXISTS status TEXT DEFAULT '참석';
