-- 1. 여행 일정(travel_schedules) 테이블 생성
CREATE TABLE travel_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Row Level Security (RLS) 활성화
ALTER TABLE travel_schedules ENABLE ROW LEVEL SECURITY;

-- 3. 누구나 데이터를 읽을 수 있도록 정책 설정
CREATE POLICY "Enable read access for all users" 
ON travel_schedules 
FOR SELECT 
USING (true);

-- 4. 누구나 데이터를 추가할 수 있도록 정책 설정
CREATE POLICY "Enable insert for all users" 
ON travel_schedules 
FOR INSERT 
WITH CHECK (true);

-- 5. 누구나 데이터를 수정할 수 있도록 정책 설정
CREATE POLICY "Enable update for all users" 
ON travel_schedules 
FOR UPDATE 
USING (true);
